name: '⚛🏗 publish'
on:
  push:
    branches:
      - main

jobs:
  release:
    name: '⚛🏗 publish'
    runs-on: ubuntu-latest
    steps:
      - name: ☑ Checkout
        uses: actions/checkout@v2.3.4
      - name: 🟩 Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: ♻ Install node modules
        run: npm i -D
      - name: ⚛ Install react and react-dom
        run: npm i react@latest react-dom@latest
      - name: 🧪 Run tests
        run: npm test
      - name: 🔨 Build /dist
        run: npm run build
      - name: 🚀 Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
